services:
  app:
    image: ghcr.io/moostoet/iprwc-backend-2025:latest
    ports:
      - "8080:8080"
    networks:
      - springapimysql
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - spring.datasource.url=jdbc:mariadb://db/iprwc-backend-2025?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - spring.datasource.username=moos
      - spring.datasource.password=moos
  db:
    image: 'linuxserver/mariadb:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=iprwc-backend-2025'
      - 'MYSQL_PASSWORD=moos'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=moos'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./healthcheck.sh:/healthcheck.sh
    networks:
      - springapimysql
    healthcheck:
      test: ["CMD", "/healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  springapimysql:

volumes:
  mysql-data: